#!/bin/bash --login
#$ -cwd
#$ -N train-ml-fb-wav2vec2-large-xlsr-53-al-F03
#$ -j y
#$ -o /work/herzig/results/train/log/hu/ml-fb-wav2vec2-large-xlsr-53/F03_al.out
#$ -l h_rt=50000
#$ -l gpus=1
#$ -l gpu_mem=22G
#$ -l ccc=6
#$ -m e
#$ -M t.herzig@campus.tu-berlin.de

conda activate /work/herzig/torch_env
module load cuda/10.1
python3 /work/herzig/asr_dysarthria/script/train_looe.py -m /work/herzig/models/ml-fb-wav2vec2-large-xlsr-53/ -l de -d hu -s 'F03'
