qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_F01.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_F02.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_F03.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_F04.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_F05.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_F06.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_M01.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_M02.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_M03.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_M04.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_M06.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_M08.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_M09.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_M10.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_M12.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_M14.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_M15.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_M16.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_M17.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_M20.job
qsub /work/herzig/job-scripts/train/train_xlsr_hu_individual_al/train_xlsr_hu_M21.job
