#!/bin/bash --login
#$ -cwd
#$ -N train_all-torgo-fb-wav2vec2-base-960h-llo
#$ -j y
#$ -o /work/herzig/results/train/log/torgo/all/torgo-fb-wav2vec2-base-960h-llo.out
#$ -l h_rt=60000
#$ -l gpus=2
#$ -l gpu_mem=22G
#$ -l ccc=6
#$ -m e
#$ -M t.herzig@campus.tu-berlin.de

conda activate /work/herzig/torch_env
module load cuda/10.1
python3 /work/herzig/asr_dysarthria/script/train_all.py -m /work/herzig/models/en-fb-wav2vec2-base-960h/ -l en -d torgo -llo True
