#!/bin/bash --login
#$ -cwd
#$ -N xlsr_train_torgo_llo_F04
#$ -j y
#$ -o /work/herzig/results/train/log/torgo_llo/F04.out
#$ -l h_rt=40000
#$ -l gpus=2
#$ -l gpu_mem=24G
#$ -l ccc=6
#$ -m e
#$ -M t.herzig@campus.tu-berlin.de

conda activate /work/herzig/torch_env
module load cuda/10.1
python3 /work/herzig/asr_dysarthria/script/train.py -m /work/herzig/models/wav2vec2-large-960h-lv60-self/ -l en -d torgo -s 'F04' -llo True
