#!/bin/bash --login
#$ -cwd
#$ -N xlsr_train_torgo_llo_MC01
#$ -j y
#$ -o /work/herzig/results/train/log/torgo_llo/MC01.out
#$ -l h_rt=30000
#$ -l gpus=2
#$ -l gpu_mem=64G
#$ -l ccc=6
#$ -m e
#$ -M t.herzig@campus.tu-berlin.de

conda activate /work/herzig/torch_env
module load cuda/10.1
python3 /work/herzig/asr_dysarthria/script/train.py -m facebook/wav2vec2-large-960h-lv60-self -l en -d torgo -s 'MC01' -llo True
