#!/bin/bash --login
#$ -cwd
#$ -N xlsr_train_hu_llo_M04
#$ -j y
#$ -o /work/herzig/results/train/log/hu_llo/M04.out
#$ -l h_rt=20000
#$ -l gpus=1
#$ -l gpu_mem=20G
#$ -l ccc=6
#$ -m e
#$ -M t.herzig@campus.tu-berlin.de

conda activate /work/herzig/torch_env
module load cuda/10.1
python3 /work/herzig/asr_dysarthria/script/train.py -m facebook/wav2vec2-large-xlsr-53-german -l de -d hu -s 'M04' -llo True
