#!/bin/bash --login
#$ -cwd
#$ -N train-en-fb-wav2vec2-base-960h-al-F01
#$ -j y
#$ -o /work/herzig/results/train/log/torgo/en-fb-wav2vec2-base-960h/F01_al.out
#$ -l h_rt=60000
#$ -l gpus=1
#$ -l gpu_mem=22G
#$ -l ccc=6
#$ -m e
#$ -M t.herzig@campus.tu-berlin.de

conda activate /work/herzig/torch_env
module load cuda/10.1
python3 /work/herzig/asr_dysarthria/script/train_torch.py -m /home/tim/Documents/Models/pre_trained/en-fb-wav2vec2-base-960h/ -l en -d uaspeech -local True
