#!/bin/bash --login
#$ -cwd
#$ -N xlsr_train_hu_M03
#$ -j y
#$ -o /work/herzig/results/train/log/hu/xlsr_M03.out
#$ -l h_rt=20000
#$ -l gpus=1
#$ -l gpu_mem=20G
#$ -l ccc=6
#$ -m e
#$ -M t.herzig@campus.tu-berlin.de

rm -f /work/herzig/results/train/log/hu/xlsr_M03.out
touch /work/herzig/results/train/log/hu/xlsr_M03.out
conda activate /work/herzig/torch_env
module load cuda/10.1
python3 /work/herzig/asr_dysarthria/script/train.py -m facebook/wav2vec2-large-xlsr-53-german -l de -d hu -s 'M03'
