#!/bin/bash --login
#$ -cwd
#$ -N train-de-wav2vec2-base-10k-voxpopuli-ft-llo-123
#$ -j y
#$ -o /work/herzig/results/train/log/hu/all/de-wav2vec2-base-10k-voxpopuli-ft-llo-123.out
#$ -l h_rt=50000
#$ -l gpus=1
#$ -l gpu_mem=22G
#$ -l ccc=6
#$ -m e
#$ -M t.herzig@campus.tu-berlin.de

conda activate /work/herzig/torch_env
module load cuda/10.1
python3 /work/herzig/asr_dysarthria/script/train_all.py -m /work/herzig/models/de-wav2vec2-base-10k-voxpopuli-ft/ -l de -d 'hu 1 2 3' -llo True
