#!/bin/bash --login
#$ -cwd
#$ -N xlsr_train_torgo_hu_al_M02
#$ -j y
#$ -o /work/herzig/results/train/log/hu_torgo_al/hu_M02.out
#$ -l h_rt=40000
#$ -l gpus=2
#$ -l gpu_mem=64G
#$ -l ccc=6
#$ -m e
#$ -M t.herzig@campus.tu-berlin.de

conda activate /work/herzig/torch_env
module load cuda/10.1
python3 /work/herzig/asr_dysarthria/script/train.py -m /work/herzig/models/wav2vec2-large-xlsr-53/ -l de -d hu -s 'M02' -sd 'torgo'
