#!/bin/bash --login
#$ -cwd
#$ -N train-de-jg-wav2vec2-large-xlsr-53-llo-M14
#$ -j y
#$ -o /work/herzig/results/train/log/hu/de-jg-wav2vec2-large-xlsr-53/M14_llo.out
#$ -l h_rt=35000
#$ -l gpus=1
#$ -l gpu_mem=16G
#$ -l ccc=6
#$ -m e
#$ -M t.herzig@campus.tu-berlin.de

conda activate /work/herzig/torch_env
module load cuda/10.1
python3 /work/herzig/asr_dysarthria/script/train.py -m /work/herzig/models/de-jg-wav2vec2-large-xlsr-53/ -l de -d hu -s 'M14' -llo True
