#!/bin/bash --login
#$ -cwd
#$ -N xlsr_train_hu_llo_M02
#$ -j y
#$ -o /work/herzig/results/train/log/failed/M02_llo.out
#$ -l h_rt=35000
#$ -l gpus=1
#$ -l gpu_mem=16G
#$ -l ccc=6
#$ -m e
#$ -M t.herzig@campus.tu-berlin.de

conda activate /work/herzig/torch_env
module load cuda/10.1
python3 /work/herzig/asr_dysarthria/script/train.py -m /work/herzig/models/wav2vec2-large-xlsr-53-german/ -l de -d hu -s 'M02' -llo True
